// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputRequestInfo struct {
	PhoneNo string `json:"phoneNo"`
}

type ResponseInfo struct {
	Status string `json:"status"`
}
